package quic

//go:generate sh -c "./mockgen_private.sh quic mock_stream_internal_test.go github.com/boisjacques/qed streamI"
//go:generate sh -c "./mockgen_private.sh quic mock_crypto_stream_test.go github.com/boisjacques/qed cryptoStream"
//go:generate sh -c "./mockgen_private.sh quic mock_receive_stream_internal_test.go github.com/boisjacques/qed receiveStreamI"
//go:generate sh -c "./mockgen_private.sh quic mock_send_stream_internal_test.go github.com/boisjacques/qed sendStreamI"
//go:generate sh -c "./mockgen_private.sh quic mock_stream_sender_test.go github.com/boisjacques/qed streamSender"
//go:generate sh -c "./mockgen_private.sh quic mock_stream_getter_test.go github.com/boisjacques/qed streamGetter"
//go:generate sh -c "./mockgen_private.sh quic mock_crypto_data_handler.go github.com/boisjacques/qed cryptoDataHandler"
//go:generate sh -c "./mockgen_private.sh quic mock_frame_source_test.go github.com/boisjacques/qed frameSource"
//go:generate sh -c "./mockgen_private.sh quic mock_ack_frame_source_test.go github.com/boisjacques/qed ackFrameSource"
//go:generate sh -c "./mockgen_private.sh quic mock_stream_manager_test.go github.com/boisjacques/qed streamManager"
//go:generate sh -c "./mockgen_private.sh quic mock_sealing_manager_test.go github.com/boisjacques/qed sealingManager"
//go:generate sh -c "./mockgen_private.sh quic mock_unpacker_test.go github.com/boisjacques/qed unpacker"
//go:generate sh -c "./mockgen_private.sh quic mock_packer_test.go github.com/boisjacques/qed packer"
//go:generate sh -c "./mockgen_private.sh quic mock_quic_aead_test.go github.com/boisjacques/qed quicAEAD"
//go:generate sh -c "./mockgen_private.sh quic mock_session_runner_test.go github.com/boisjacques/qed sessionRunner"
//go:generate sh -c "./mockgen_private.sh quic mock_quic_session_test.go github.com/boisjacques/qed quicSession"
//go:generate sh -c "./mockgen_private.sh quic mock_packet_handler_test.go github.com/boisjacques/qed packetHandler"
//go:generate sh -c "./mockgen_private.sh quic mock_unknown_packet_handler_test.go github.com/boisjacques/qed unknownPacketHandler"
//go:generate sh -c "./mockgen_private.sh quic mock_packet_handler_manager_test.go github.com/boisjacques/qed packetHandlerManager"
//go:generate sh -c "./mockgen_private.sh quic mock_multiplexer_test.go github.com/boisjacques/qed multiplexer"
